language: php

php:
  - 7.0
  - 7.1

matrix:
  allow_failures:
    - php: 7.1

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS="--prefer-stable"

install:
  - composer self-update
  - composer update --no-interaction --prefer-source $COMPOSER_FLAGS

script: vendor/bin/phpunit

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3ffa605389816ec39774
    on_success: change
    on_failure: always
    on_start: never
