blank_issues_enabled: false
contact_links:
  - name: Ask question
    url: https://github.com/deployphp/deployer/discussions/category_choices
    about: Please ask and answer questions in discussions
